[2024-02-12T10:53:32.303+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:53:32.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:53:32.306+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:53:32.306+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:53:32.309+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:53:32.309+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:53:32.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:53:32.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.028 seconds
[2024-02-12T10:54:02.450+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:54:02.451+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:54:02.454+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:54:02.453+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:54:02.458+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:54:02.456+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:54:02.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:54:02.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.029 seconds
[2024-02-12T10:54:32.822+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:54:32.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:54:32.830+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:54:32.829+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:54:32.836+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:54:32.833+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:54:32.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:54:32.895+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.082 seconds
[2024-02-12T10:55:02.966+0000] {processor.py:161} INFO - Started process (PID=204) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:55:02.968+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:55:02.971+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:55:02.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:55:02.976+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:55:02.974+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:55:02.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:55:02.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.039 seconds
[2024-02-12T10:55:33.173+0000] {processor.py:161} INFO - Started process (PID=260) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:55:33.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:55:33.178+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:55:33.177+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:55:33.183+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:55:33.182+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:55:33.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:55:33.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.035 seconds
[2024-02-12T10:56:03.356+0000] {processor.py:161} INFO - Started process (PID=316) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:56:03.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:56:03.361+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:56:03.361+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:56:03.365+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:56:03.364+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:56:03.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:56:03.385+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.035 seconds
[2024-02-12T10:56:33.411+0000] {processor.py:161} INFO - Started process (PID=371) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:56:33.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:56:33.415+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:56:33.415+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:56:33.421+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:56:33.419+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:56:33.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:56:33.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.042 seconds
[2024-02-12T10:57:04.003+0000] {processor.py:161} INFO - Started process (PID=428) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:57:04.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:57:04.005+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:57:04.005+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:57:04.010+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:57:04.008+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:57:04.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:57:04.035+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.035 seconds
[2024-02-12T10:57:34.427+0000] {processor.py:161} INFO - Started process (PID=484) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:57:34.429+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:57:34.431+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:57:34.431+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:57:34.440+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:57:34.436+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:57:34.441+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:57:34.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.058 seconds
[2024-02-12T10:58:04.789+0000] {processor.py:161} INFO - Started process (PID=540) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:58:04.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:58:04.796+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:58:04.796+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:58:04.805+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:58:04.803+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:58:04.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:58:04.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.052 seconds
[2024-02-12T10:58:34.947+0000] {processor.py:161} INFO - Started process (PID=596) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:58:34.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:58:34.956+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:58:34.955+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:58:34.964+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:58:34.962+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:58:34.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:58:34.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.053 seconds
[2024-02-12T10:59:05.062+0000] {processor.py:161} INFO - Started process (PID=652) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:59:05.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:59:05.071+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:59:05.070+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:59:05.079+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:59:05.078+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:59:05.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:59:05.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.050 seconds
[2024-02-12T10:59:35.501+0000] {processor.py:161} INFO - Started process (PID=708) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:59:35.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:59:35.524+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:59:35.523+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:59:35.535+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:59:35.531+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:59:35.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:59:35.564+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.078 seconds
[2024-02-12T11:00:06.094+0000] {processor.py:161} INFO - Started process (PID=764) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:00:06.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:00:06.097+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:00:06.097+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:00:06.101+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:00:06.100+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:00:06.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:00:06.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.029 seconds
[2024-02-12T11:00:36.653+0000] {processor.py:161} INFO - Started process (PID=820) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:00:36.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:00:36.656+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:00:36.656+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:00:36.659+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:00:36.658+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:00:36.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:00:36.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.024 seconds
[2024-02-12T11:01:07.042+0000] {processor.py:161} INFO - Started process (PID=877) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:01:07.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:01:07.052+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:01:07.051+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:01:07.061+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:01:07.059+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:01:07.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:01:07.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.053 seconds
[2024-02-12T11:01:37.183+0000] {processor.py:161} INFO - Started process (PID=933) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:01:37.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:01:37.193+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:01:37.192+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:01:37.204+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:01:37.202+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:01:37.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:01:37.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.098 seconds
[2024-02-12T11:02:07.407+0000] {processor.py:161} INFO - Started process (PID=989) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:02:07.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:02:07.410+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:02:07.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:02:07.413+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:02:07.413+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:02:07.414+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:02:07.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.031 seconds
[2024-02-12T11:02:37.920+0000] {processor.py:161} INFO - Started process (PID=1045) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:02:37.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:02:37.924+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:02:37.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:02:37.929+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:02:37.927+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:02:37.929+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:02:37.956+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.042 seconds
[2024-02-12T11:03:08.254+0000] {processor.py:161} INFO - Started process (PID=1101) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:03:08.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:03:08.263+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:03:08.263+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:03:08.270+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:03:08.268+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:03:08.271+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:03:08.291+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.049 seconds
[2024-02-12T11:03:38.511+0000] {processor.py:161} INFO - Started process (PID=1157) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:03:38.513+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:03:38.514+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:03:38.514+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:03:38.518+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:03:38.517+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:03:38.518+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:03:38.539+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.031 seconds
[2024-02-12T11:04:08.924+0000] {processor.py:161} INFO - Started process (PID=1213) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:04:08.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:04:08.928+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:04:08.927+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:04:08.934+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:04:08.932+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:04:08.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:04:08.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.044 seconds
[2024-02-12T11:04:39.090+0000] {processor.py:161} INFO - Started process (PID=1269) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:04:39.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:04:39.094+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:04:39.094+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:04:39.098+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:04:39.097+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:04:39.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:04:39.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.037 seconds
[2024-02-12T11:05:09.992+0000] {processor.py:161} INFO - Started process (PID=1325) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:05:09.993+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:05:09.995+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:05:09.994+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:05:10.000+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:05:09.998+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:05:10.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:05:10.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.033 seconds
[2024-02-12T11:05:40.076+0000] {processor.py:161} INFO - Started process (PID=1380) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:05:40.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:05:40.078+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:05:40.078+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:05:40.081+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:05:40.081+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:05:40.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:05:40.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.026 seconds
[2024-02-12T11:06:00.697+0000] {processor.py:161} INFO - Started process (PID=1434) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:06:00.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:06:00.713+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:00.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:06:00.740+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:06:00.977+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:00.976+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:consumer_dag
[2024-02-12T11:06:00.991+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:00.990+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:consumer_dag
[2024-02-12T11:06:00.998+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:00.998+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:consumer_dag
[2024-02-12T11:06:00.998+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:00.998+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:06:01.013+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:01.013+0000] {dag.py:3058} INFO - Creating ORM DAG for consumer_dag
[2024-02-12T11:06:01.026+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:01.026+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:06:01.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.379 seconds
[2024-02-12T11:06:31.321+0000] {processor.py:161} INFO - Started process (PID=1490) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:06:31.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:06:31.325+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:31.325+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:06:31.333+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:06:31.352+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:31.352+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:06:31.373+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:31.372+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:06:31.389+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.075 seconds
[2024-02-12T11:07:01.439+0000] {processor.py:161} INFO - Started process (PID=1547) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:01.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:07:01.443+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:07:01.443+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:01.450+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:01.473+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:07:01.472+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:07:01.493+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:07:01.493+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:07:01.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.078 seconds
[2024-02-12T11:07:08.553+0000] {processor.py:161} INFO - Started process (PID=1548) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:08.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:07:08.565+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:07:08.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:08.592+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:07:08.587+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:07:08.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:08.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.158 seconds
[2024-02-12T11:07:39.660+0000] {processor.py:161} INFO - Started process (PID=1605) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:39.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:07:39.664+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:07:39.664+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:39.667+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:07:39.666+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:07:39.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:39.685+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.028 seconds
[2024-02-12T11:08:10.003+0000] {processor.py:161} INFO - Started process (PID=1662) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:08:10.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:08:10.007+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:08:10.007+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:08:10.010+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:08:10.010+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:08:10.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:08:10.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.029 seconds
[2024-02-12T11:08:40.852+0000] {processor.py:161} INFO - Started process (PID=1718) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:08:40.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:08:40.855+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:08:40.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:08:40.859+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:08:40.858+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:08:40.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:08:40.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.028 seconds
[2024-02-12T11:09:10.924+0000] {processor.py:161} INFO - Started process (PID=1774) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:09:10.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:09:10.927+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:09:10.926+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:09:10.930+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:09:10.929+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:09:10.931+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:09:10.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.028 seconds
[2024-02-12T11:09:41.385+0000] {processor.py:161} INFO - Started process (PID=1830) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:09:41.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:09:41.390+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:09:41.389+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:09:41.395+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:09:41.394+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:09:41.396+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:09:41.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.037 seconds
[2024-02-12T11:10:12.133+0000] {processor.py:161} INFO - Started process (PID=1886) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:10:12.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:10:12.134+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:10:12.134+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:10:12.137+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:10:12.136+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:10:12.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:10:12.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.025 seconds
[2024-02-12T11:10:42.201+0000] {processor.py:161} INFO - Started process (PID=1942) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:10:42.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:10:42.205+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:10:42.204+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:10:42.209+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:10:42.208+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:10:42.210+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:10:42.229+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.036 seconds
[2024-02-12T11:11:13.091+0000] {processor.py:161} INFO - Started process (PID=1998) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:11:13.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:11:13.094+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:11:13.094+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:11:13.099+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:11:13.098+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:11:13.100+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:11:13.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.034 seconds
[2024-02-12T11:11:43.261+0000] {processor.py:161} INFO - Started process (PID=2053) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:11:43.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:11:43.265+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:11:43.265+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:11:43.275+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:11:43.271+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:11:43.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:11:43.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.075 seconds
[2024-02-12T11:12:13.556+0000] {processor.py:161} INFO - Started process (PID=2110) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:12:13.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:12:13.558+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:12:13.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:12:13.563+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:12:13.562+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:12:13.564+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:12:13.584+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.031 seconds
[2024-02-12T11:12:43.936+0000] {processor.py:161} INFO - Started process (PID=2166) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:12:43.938+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:12:43.940+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:12:43.939+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:12:43.944+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:12:43.943+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:12:43.945+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:12:43.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.036 seconds
[2024-02-12T11:13:14.312+0000] {processor.py:161} INFO - Started process (PID=2222) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:13:14.314+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:13:14.315+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:13:14.315+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:13:14.322+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:13:14.320+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:13:14.322+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:13:14.358+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.053 seconds
[2024-02-12T11:13:45.234+0000] {processor.py:161} INFO - Started process (PID=2277) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:13:45.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:13:45.237+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:13:45.237+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:13:45.243+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:13:45.241+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:13:45.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:13:45.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.041 seconds
[2024-02-12T11:14:15.595+0000] {processor.py:161} INFO - Started process (PID=2333) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:14:15.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:14:15.599+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:14:15.599+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:14:15.604+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:14:15.603+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:14:15.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:14:15.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.039 seconds
[2024-02-12T11:14:45.956+0000] {processor.py:161} INFO - Started process (PID=2389) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:14:45.957+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:14:45.957+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:14:45.957+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:14:45.960+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:14:45.959+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:14:45.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:14:45.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.023 seconds
[2024-02-12T11:15:16.261+0000] {processor.py:161} INFO - Started process (PID=2445) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:15:16.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:15:16.263+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:15:16.263+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:15:16.267+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:15:16.266+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:15:16.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:15:16.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.026 seconds
[2024-02-12T11:15:46.930+0000] {processor.py:161} INFO - Started process (PID=2501) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:15:46.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:15:46.934+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:15:46.933+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:15:46.939+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:15:46.937+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:15:46.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:15:46.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.044 seconds
[2024-02-12T11:16:17.392+0000] {processor.py:161} INFO - Started process (PID=2557) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:16:17.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:16:17.397+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:16:17.396+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:16:17.403+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:16:17.402+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:16:17.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:16:17.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.039 seconds
[2024-02-12T11:16:47.634+0000] {processor.py:161} INFO - Started process (PID=2613) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:16:47.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:16:47.637+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:16:47.637+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:16:47.641+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:16:47.640+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:16:47.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:16:47.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.043 seconds
[2024-02-12T11:17:18.134+0000] {processor.py:161} INFO - Started process (PID=2669) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:17:18.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:17:18.136+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:17:18.136+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:17:18.141+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:17:18.139+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:17:18.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:17:18.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.048 seconds
[2024-02-12T11:17:48.443+0000] {processor.py:161} INFO - Started process (PID=2725) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:17:48.444+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:17:48.445+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:17:48.444+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:17:48.447+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:17:48.446+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:17:48.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:17:48.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.024 seconds
[2024-02-12T11:18:18.735+0000] {processor.py:161} INFO - Started process (PID=2781) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:18:18.736+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:18:18.736+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:18:18.736+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:18:18.740+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:18:18.739+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:18:18.740+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:18:18.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.026 seconds
[2024-02-12T11:18:49.322+0000] {processor.py:161} INFO - Started process (PID=2846) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:18:49.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:18:49.325+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:18:49.325+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:18:49.330+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:18:49.329+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:18:49.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:18:49.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.034 seconds
[2024-02-12T11:19:19.814+0000] {processor.py:161} INFO - Started process (PID=2939) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:19:19.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:19:19.816+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:19:19.815+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:19:19.822+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:19:19.821+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:19:19.823+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:19:19.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.030 seconds
[2024-02-12T11:19:50.367+0000] {processor.py:161} INFO - Started process (PID=2995) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:19:50.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:19:50.370+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:19:50.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:19:50.376+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:19:50.375+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:19:50.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:19:50.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.040 seconds
[2024-02-12T11:20:20.914+0000] {processor.py:161} INFO - Started process (PID=3089) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:20:20.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:20:20.917+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:20:20.917+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:20:20.966+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:20:20.965+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-02-12T11:20:20.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:20:20.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.081 seconds
[2024-02-12T11:20:51.603+0000] {processor.py:161} INFO - Started process (PID=3145) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:20:51.604+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:20:51.606+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:20:51.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:20:51.689+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:20:51.823+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:20:51.822+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:20:51.851+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:20:51.851+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:20:51.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.288 seconds
[2024-02-12T11:21:22.473+0000] {processor.py:161} INFO - Started process (PID=3206) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:21:22.474+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:21:22.475+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:21:22.475+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:21:22.563+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:21:22.627+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:21:22.627+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:21:22.664+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:21:22.663+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:21:22.684+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.214 seconds
[2024-02-12T11:21:53.039+0000] {processor.py:161} INFO - Started process (PID=3262) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:21:53.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:21:53.050+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:21:53.047+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:21:53.260+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:21:53.355+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:21:53.355+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:21:53.419+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:21:53.419+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:21:53.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.433 seconds
[2024-02-12T11:22:23.967+0000] {processor.py:161} INFO - Started process (PID=3318) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:22:23.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:22:23.972+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:22:23.971+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:22:24.173+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:22:24.252+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:22:24.250+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:22:24.334+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:22:24.333+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:22:24.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.438 seconds
[2024-02-12T11:22:27.047+0000] {processor.py:161} INFO - Started process (PID=3319) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:22:27.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:22:27.049+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:22:27.049+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:22:27.174+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:22:27.895+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:22:27.891+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:22:27.978+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:22:27.977+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:22:28.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 1.032 seconds
[2024-02-12T11:23:07.205+0000] {processor.py:161} INFO - Started process (PID=3374) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:23:07.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:23:07.225+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:23:07.219+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:23:07.557+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:23:07.633+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:23:07.631+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:23:07.710+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:23:07.710+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:23:07.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.585 seconds
[2024-02-12T11:30:27.100+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:30:27.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:30:27.102+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:30:27.102+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:30:27.186+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:30:27.253+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:30:27.253+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:30:27.309+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:30:27.309+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T11:30:27.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.238 seconds
