[2024-02-13T12:13:08.358+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T03:50:00+00:00 [queued]>
[2024-02-13T12:13:08.467+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T03:50:00+00:00 [queued]>
[2024-02-13T12:13:08.481+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-13T12:13:08.732+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): consumer_task> on 2024-02-12 03:50:00+00:00
[2024-02-13T12:13:08.744+0000] {standard_task_runner.py:60} INFO - Started process 165 to run task
[2024-02-13T12:13:08.757+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'baserowdata', 'consumer_task', 'scheduled__2024-02-12T03:50:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/consumer_dag.py', '--cfg-path', '/tmp/tmpgd50piqn']
[2024-02-13T12:13:08.762+0000] {standard_task_runner.py:88} INFO - Job 32: Subtask consumer_task
[2024-02-13T12:13:09.106+0000] {task_command.py:423} INFO - Running <TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T03:50:00+00:00 [running]> on host b9c9154d9bc2
[2024-02-13T12:13:09.413+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='baserowdata' AIRFLOW_CTX_TASK_ID='consumer_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T03:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T03:50:00+00:00'
[2024-02-13T12:13:09.976+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:10.752+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:10.761+0000] {logging_mixin.py:188} INFO - CSV dosyasında veri bulunmuyor. 10 dakika sonra tekrar kontrol edilecek.
[2024-02-13T12:13:10.761+0000] {logging_mixin.py:188} INFO - CSV dosyasında veri bulunmuyor. 10 dakika sonra tekrar kontrol edilecek.
[2024-02-13T12:13:10.762+0000] {logging_mixin.py:188} INFO - CSV dosyasında veri bulunmuyor. 10 dakika sonra tekrar kontrol edilecek.
[2024-02-13T12:13:11.413+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:11.994+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:12.718+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:12.725+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/consumer_dag.py", line 38, in main
    rows = list(reader)  # CSV dosyasındaki tüm satırları al
  File "/usr/local/lib/python3.8/csv.py", line 110, in __next__
    self.fieldnames
  File "/usr/local/lib/python3.8/csv.py", line 97, in fieldnames
    self._fieldnames = next(self.reader)
_csv.Error: line contains NUL
[2024-02-13T12:13:12.815+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=baserowdata, task_id=consumer_task, execution_date=20240212T035000, start_date=20240213T121308, end_date=20240213T121312
[2024-02-13T12:13:13.003+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 32 for task consumer_task (line contains NUL; 165)
[2024-02-13T12:13:13.082+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-13T12:13:13.137+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
