[2024-02-13T12:12:31.136+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T01:20:00+00:00 [queued]>
[2024-02-13T12:12:31.280+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T01:20:00+00:00 [queued]>
[2024-02-13T12:12:31.283+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-13T12:12:31.417+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): consumer_task> on 2024-02-12 01:20:00+00:00
[2024-02-13T12:12:31.454+0000] {standard_task_runner.py:60} INFO - Started process 117 to run task
[2024-02-13T12:12:31.503+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'baserowdata', 'consumer_task', 'scheduled__2024-02-12T01:20:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/consumer_dag.py', '--cfg-path', '/tmp/tmpaqivepnc']
[2024-02-13T12:12:31.507+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask consumer_task
[2024-02-13T12:12:31.845+0000] {task_command.py:423} INFO - Running <TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T01:20:00+00:00 [running]> on host b9c9154d9bc2
[2024-02-13T12:12:32.793+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='baserowdata' AIRFLOW_CTX_TASK_ID='consumer_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T01:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T01:20:00+00:00'
[2024-02-13T12:12:33.540+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:34.158+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:34.765+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:35.474+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:35.503+0000] {logging_mixin.py:188} INFO - CSV dosyasında veri bulunmuyor. 10 dakika sonra tekrar kontrol edilecek.
[2024-02-13T12:12:36.240+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:37.362+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:38.131+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:38.752+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:39.833+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:40.751+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:41.412+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:42.051+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:42.618+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:43.185+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:43.943+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:44.624+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:45.261+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:45.273+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/consumer_dag.py", line 38, in main
    rows = list(reader)  # CSV dosyasındaki tüm satırları al
  File "/usr/local/lib/python3.8/csv.py", line 110, in __next__
    self.fieldnames
  File "/usr/local/lib/python3.8/csv.py", line 97, in fieldnames
    self._fieldnames = next(self.reader)
_csv.Error: line contains NUL
[2024-02-13T12:12:45.296+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=baserowdata, task_id=consumer_task, execution_date=20240212T012000, start_date=20240213T121231, end_date=20240213T121245
[2024-02-13T12:12:45.355+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 17 for task consumer_task (line contains NUL; 117)
[2024-02-13T12:12:45.404+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-13T12:12:45.479+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
