[2024-02-13T12:12:27.996+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T00:10:00+00:00 [queued]>
[2024-02-13T12:12:28.109+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T00:10:00+00:00 [queued]>
[2024-02-13T12:12:28.109+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-13T12:12:28.352+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): consumer_task> on 2024-02-12 00:10:00+00:00
[2024-02-13T12:12:28.472+0000] {standard_task_runner.py:60} INFO - Started process 106 to run task
[2024-02-13T12:12:28.524+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'baserowdata', 'consumer_task', 'scheduled__2024-02-12T00:10:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/consumer_dag.py', '--cfg-path', '/tmp/tmpzm8epitt']
[2024-02-13T12:12:28.546+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask consumer_task
[2024-02-13T12:12:28.978+0000] {task_command.py:423} INFO - Running <TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T00:10:00+00:00 [running]> on host b9c9154d9bc2
[2024-02-13T12:12:29.668+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='baserowdata' AIRFLOW_CTX_TASK_ID='consumer_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T00:10:00+00:00'
[2024-02-13T12:12:30.955+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:32.431+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:33.293+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:33.988+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:34.755+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:36.470+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:37.264+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:37.929+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:38.591+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:39.354+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:39.952+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:40.808+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:41.435+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:42.101+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:42.710+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:43.256+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:43.929+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:44.772+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:45.327+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:46.022+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:46.678+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:47.275+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:47.804+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:48.256+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:48.750+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:48.755+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/consumer_dag.py", line 66, in main
    writer.writerows(rows)
  File "/usr/local/lib/python3.8/csv.py", line 157, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
  File "/usr/local/lib/python3.8/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: None
[2024-02-13T12:12:48.774+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=baserowdata, task_id=consumer_task, execution_date=20240212T001000, start_date=20240213T121227, end_date=20240213T121248
[2024-02-13T12:12:48.819+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task consumer_task (dict contains fields not in fieldnames: None; 106)
[2024-02-13T12:12:48.852+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-13T12:12:48.946+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
