[2024-02-13T12:12:28.349+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T00:40:00+00:00 [queued]>
[2024-02-13T12:12:28.514+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T00:40:00+00:00 [queued]>
[2024-02-13T12:12:28.515+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-13T12:12:28.709+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): consumer_task> on 2024-02-12 00:40:00+00:00
[2024-02-13T12:12:28.744+0000] {standard_task_runner.py:60} INFO - Started process 109 to run task
[2024-02-13T12:12:28.778+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'baserowdata', 'consumer_task', 'scheduled__2024-02-12T00:40:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/consumer_dag.py', '--cfg-path', '/tmp/tmpkmm8wiqt']
[2024-02-13T12:12:28.806+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask consumer_task
[2024-02-13T12:12:29.585+0000] {task_command.py:423} INFO - Running <TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T00:40:00+00:00 [running]> on host b9c9154d9bc2
[2024-02-13T12:12:30.280+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='baserowdata' AIRFLOW_CTX_TASK_ID='consumer_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T00:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T00:40:00+00:00'
[2024-02-13T12:12:31.101+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:31.913+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:32.970+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:33.664+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:34.360+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:34.979+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:35.659+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:12:35.675+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/consumer_dag.py", line 66, in main
    writer.writerows(rows)
  File "/usr/local/lib/python3.8/csv.py", line 157, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
  File "/usr/local/lib/python3.8/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: None
[2024-02-13T12:12:35.726+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=baserowdata, task_id=consumer_task, execution_date=20240212T004000, start_date=20240213T121228, end_date=20240213T121235
[2024-02-13T12:12:36.230+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task consumer_task (dict contains fields not in fieldnames: None; 109)
[2024-02-13T12:12:36.280+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-13T12:12:36.361+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
